name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # packages下は設定ファイルしかないので、対象外にしてる
        workspace: [apps/app, apps/admin]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run linter
        run: bun workspace ${{ matrix.workspace }} lint
